# Generated by Django 5.1.1 on 2024-10-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nick_name',
        ),
    ]
